spring:
  application:
    name: processor
  cloud:
    nacos:
      server-addr: 47.99.243.32:8848
      discovery:
        server-addr: 47.99.243.32:8848
      config:
        server-addr: 47.99.243.32:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.99.243.32:3306/tigrex?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: tigrex
      password: 123456
server:
  port: 61304